#.travis.yml
dist: trusty
sudo: false

language: node_js
node_js:
  - "node"
# addons:
#   apt:
#     sources:
#       - google-chrome
#     packages:
#       - google-chrome-stable

cache:
  directories:
    - ./node_modules
branches:
  only:
    - master

before_script:
  - npm install -g yarn@1.15.2 firebase-tools@6.5.0 @angular/cli@7.3.3 typescript@3.2.4 tslint@5.12.1
script:
  - ng build --prod 
  # - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox

  - firebase deploy --token $FIREBASE_TOKEN
after_success:

notifications:
  email:
    on_failure: change
    on_success: change
